#!/bin/bash

function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    dunstify -r 2593 -u normal "    $bar"
}

case $1 in
    up)
	# Set the volume on (if it was muted)
	amixer -q set Master 5%+ unmute > /dev/null
	send_notification
	;;
    down)
	amixer -q set Master 5%- unmute > /dev/null
	send_notification
	;;
    mute)
    	# Toggle mute
	amixer set Master toggle > /dev/null
	if is_mute ; then
	    dunstify -r 2593 -u normal "Muted"
	else
	    send_notification
	fi
	;;

    mic)
	amixer set Capture toggle > /dev/null
	if is_mute ; then
            dunstify -r 2593 -u normal "Mic muted"
        else
            send_notification
        fi
        ;;
esac
